import { NextResponse } from "next/server";

export const dynamic = "force-dynamic";

const symbols={sp500:"^GSPC",qqqm:"QQQM",nikkei:"^N225",taiwan:"^TWII",usdjpy:"JPY=X",cnyjpy:"CNYJPY=X",twdjpy:"TWDJPY=X"};
const places={kinshicho:{lat:35.6967,lon:139.8142},shibuya:{lat:35.6595,lon:139.7005},kuwana:{lat:35.0622,lon:136.6838}};
function md(ts,tz){return new Intl.DateTimeFormat("en-CA",{timeZone:tz,month:"2-digit",day:"2-digit"}).format(new Date(ts*1000)).replace("-","/")}
function weekly(rows,tz){const out=[],bucket=[];for(const r of rows){const d=new Date(r[0]*1000),parts=new Intl.DateTimeFormat("en-CA",{timeZone:tz,year:"numeric",month:"2-digit",day:"2-digit",weekday:"short"}).formatToParts(d);const o=Object.fromEntries(parts.map(x=>[x.type,x.value]));const local=new Date(`${o.year}-${o.month}-${o.day}T00:00:00Z`);const day=local.getUTCDay();const mon=new Date(local);mon.setUTCDate(local.getUTCDate()-((day+6)%7));const key=mon.toISOString().slice(0,10);if(bucket.length&&bucket[bucket.length-1].key!==key){const z=bucket[bucket.length-1].row;out.push([md(z[0],tz),+z[1].toFixed(4)]);bucket.length=0}bucket.push({key,row:r})}if(bucket.length){const z=bucket[bucket.length-1].row;out.push([md(z[0],tz),+z[1].toFixed(4)])}return out}
async function yahoo(symbol){const u=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?range=1y&interval=1d&includePrePost=false&events=div%2Csplits`;const r=await fetch(u,{cache:"no-store",headers:{"User-Agent":"Mozilla/5.0"}});if(!r.ok)throw new Error(`Yahoo ${symbol}: ${r.status}`);const j=await r.json(),x=j?.chart?.result?.[0];if(!x)throw new Error(`Yahoo ${symbol}: empty`);const c=x.indicators?.quote?.[0]?.close||[],rows=(x.timestamp||[]).map((ts,i)=>[ts,c[i]]).filter(v=>Number.isFinite(v[1]));const tz=x.meta?.exchangeTimezoneName||"UTC",last=rows.at(-1),prev=rows.at(-2),cut=last[0]-37*86400,m=rows.filter(v=>v[0]>=cut).map(v=>[md(v[0],tz),+v[1].toFixed(4)]);return{last:+last[1].toFixed(4),prev:+prev[1].toFixed(4),asof:md(last[0],tz),m,y:weekly(rows,tz)}}
function wname(code,p){if(code>=95)return"雷雨";if(p>=4)return"強雨";if([80,81,82].includes(code))return"驟雨";if(code>=61)return"雨";if(code>=51)return"小雨";if(code===0)return"晴";if(code<=2)return"晴時々曇";return"曇"}
const wd=["日","一","二","三","四","五","六"];
async function weather({lat,lon}){const q=new URLSearchParams({latitude:String(lat),longitude:String(lon),timezone:"Asia/Tokyo",forecast_days:"7",hourly:"temperature_2m,relative_humidity_2m,precipitation,precipitation_probability,weather_code,wind_speed_10m,uv_index",daily:"weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,wind_speed_10m_max,uv_index_max"});const r=await fetch(`https://api.open-meteo.com/v1/forecast?${q}`,{cache:"no-store"});if(!r.ok)throw new Error(`OpenMeteo ${lat},${lon}: ${r.status}`);const j=await r.json(),date=j.daily.time[0],h=[];for(let i=0;i<j.hourly.time.length;i++){if(!j.hourly.time[i].startsWith(date))continue;const p=j.hourly.precipitation[i]||0;h.push([+j.hourly.time[i].slice(11,13),j.hourly.temperature_2m[i],p,j.hourly.wind_speed_10m[i],wname(j.hourly.weather_code[i],p),j.hourly.uv_index[i]])}const d=j.daily.time.map((x,i)=>{const idx=j.hourly.time.findIndex(t=>t.startsWith(x));const hs=j.hourly.relative_humidity_2m.slice(idx,idx+24).filter(Number.isFinite);const hum=hs.length?Math.round(hs.reduce((a,b)=>a+b,0)/hs.length):null;return[x.slice(5).replace("-","/"),wd[new Date(`${x}T00:00:00+09:00`).getDay()],wname(j.daily.weather_code[i],0),j.daily.temperature_2m_max[i],j.daily.temperature_2m_min[i],j.daily.precipitation_probability_max[i],`最高${j.daily.precipitation_probability_max[i]}%`,j.daily.wind_speed_10m_max[i],hum,j.daily.uv_index_max[i],null]});return{hourly:h,daily:d}}
export async function GET(){try{const ms=Object.fromEntries(await Promise.all(Object.entries(symbols).map(async([k,s])=>[k,await yahoo(s)])));const ws=Object.fromEntries(await Promise.all(Object.entries(places).map(async([k,p])=>[k,await weather(p)])));const N={sp500:"S&P 500",qqqm:"QQQM",nikkei:"日經 225",taiwan:"台灣加權",usdjpy:"USD/JPY",cnyjpy:"CNY/JPY",twdjpy:"TWD/JPY"};const map=k=>({name:N[k],...ms[k]});return NextResponse.json({fetchedAt:new Date().toISOString(),date:new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()),w:{"錦糸町（墨田區）":ws.kinshicho,"澀谷":ws.shibuya,"桑名（三重縣桑名市）":ws.kuwana},s:[map("sp500"),map("qqqm"),map("nikkei"),map("taiwan")],f:[map("usdjpy"),map("cnyjpy"),map("twdjpy")]});}catch(e){return NextResponse.json({error:String(e?.message||e)},{status:500})}}
