-- 相册多用户改造：建立相册与用户关联表
create table public.album_user (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    album_id bigint not null references public.album(id) on delete cascade,
    user_id uuid not null references public.f_user(id) on delete restrict,
    role text not null default 'participant' check (role in ('creator', 'participant')),
    unique (album_id, user_id)
);

comment on table public.album_user is '相册与用户的关联表，支持一张照片关联多个用户';
comment on column public.album_user.id is '关联记录主键';
comment on column public.album_user.created_at is '创建时间';
comment on column public.album_user.album_id is '相册 ID';
comment on column public.album_user.user_id is '用户 ID';
comment on column public.album_user.role is '用户在照片中的角色：creator 创建者，participant 参与者';

-- 每张照片只能有一名创建者
create unique index album_user_one_creator_idx
    on public.album_user (album_id)
    where role = 'creator';

create index album_user_user_id_idx
    on public.album_user (user_id);

-- 不启用 RLS，也不加入 Realtime publication
alter table public.album_user disable row level security;

grant select, insert, update, delete on table public.album_user
    to anon, authenticated;

grant all privileges on table public.album_user
    to service_role;

grant usage, select, update on sequence public.album_user_id_seq
    to anon, authenticated, service_role;

-- 数据迁移：将旧 album.userId 写入关联表，角色为创建者
insert into public.album_user (album_id, user_id, role)
select
    album.id,
    album."userId",
    'creator'
from public.album as album
where album."userId" is not null
on conflict (album_id, user_id)
do update set role = excluded.role;

-- 后续新增照片时，同步写入创建者关联记录：
-- insert into public.album_user (album_id, user_id, role)
-- values (:album_id, :user_id, 'creator');
