create table public.user_nutrition_target (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null unique references public.f_user(id),
  sex text not null, birth_date date not null, age integer not null, age_band text not null,
  height_cm numeric(5, 2) not null, current_weight_kg numeric(6, 2) not null,
  target_weight_kg numeric(6, 2) not null, reference_weight_kg numeric(6, 2) not null,
  body_fat_pct numeric(5, 2), activity text not null, bmi numeric(5, 2) not null,
  menstruation text, ckd_stage text,
  walking_kcal_per_step numeric(8, 4),
  goals jsonb not null default '[]'::jsonb, health_tags jsonb not null default '[]'::jsonb,
  applied_rules jsonb not null default '{}'::jsonb,
  energy_kcal_min numeric(10, 2), energy_kcal_max numeric(10, 2),
  protein_g_min numeric(10, 2), protein_g_max numeric(10, 2),
  fat_g_min numeric(10, 2), fat_g_max numeric(10, 2), saturated_fat_g_max numeric(10, 2),
  carbohydrate_g_min numeric(10, 2), carbohydrate_g_max numeric(10, 2), dietary_fiber_g_min numeric(10, 2),
  vitamin_a_ug_rae_min numeric(10, 2), vitamin_b1_mg_min numeric(10, 2), vitamin_b2_mg_min numeric(10, 2),
  vitamin_b6_mg_min numeric(10, 2), vitamin_b12_ug_min numeric(10, 2), vitamin_c_mg_min numeric(10, 2),
  vitamin_d_ug_target numeric(10, 2), calcium_mg_min numeric(10, 2), iron_mg_min numeric(10, 2),
  sodium_mg_max numeric(10, 2), salt_equivalent_g_max numeric(10, 2), potassium_mg_min numeric(10, 2),
  constraint user_nutrition_target_goals_is_array check (jsonb_typeof(goals) = 'array'),
  constraint user_nutrition_target_health_tags_is_array check (jsonb_typeof(health_tags) = 'array'),
  constraint user_nutrition_target_applied_rules_is_object check (jsonb_typeof(applied_rules) = 'object')
);

comment on table public.user_nutrition_target is '用户个性化营养目标';
comment on column public.user_nutrition_target.id is '主键';
comment on column public.user_nutrition_target.created_at is '创建时间';
comment on column public.user_nutrition_target.user_id is '用户ID';
comment on column public.user_nutrition_target.sex is '生理性别';
comment on column public.user_nutrition_target.birth_date is '出生日期';
comment on column public.user_nutrition_target.age is '年龄';
comment on column public.user_nutrition_target.age_band is '年龄段';
comment on column public.user_nutrition_target.height_cm is '身高（厘米）';
comment on column public.user_nutrition_target.current_weight_kg is '当前体重（千克）';
comment on column public.user_nutrition_target.target_weight_kg is '目标体重（千克）';
comment on column public.user_nutrition_target.reference_weight_kg is '营养计算参考体重（千克）';
comment on column public.user_nutrition_target.body_fat_pct is '体脂率（百分比）';
comment on column public.user_nutrition_target.activity is '身体活动水平';
comment on column public.user_nutrition_target.bmi is '身体质量指数';
comment on column public.user_nutrition_target.menstruation is '月经状态';
comment on column public.user_nutrition_target.ckd_stage is '慢性肾病分期';
comment on column public.user_nutrition_target.walking_kcal_per_step is '每步步行消耗（千卡）';
comment on column public.user_nutrition_target.goals is '健康目标列表';
comment on column public.user_nutrition_target.health_tags is '健康标签列表';
comment on column public.user_nutrition_target.applied_rules is '已应用规则';
comment on column public.user_nutrition_target.energy_kcal_min is '每日热量下限（千卡）';
comment on column public.user_nutrition_target.energy_kcal_max is '每日热量上限（千卡）';
comment on column public.user_nutrition_target.protein_g_min is '每日蛋白质下限（克）';
comment on column public.user_nutrition_target.protein_g_max is '每日蛋白质上限（克）';
comment on column public.user_nutrition_target.fat_g_min is '每日脂肪下限（克）';
comment on column public.user_nutrition_target.fat_g_max is '每日脂肪上限（克）';
comment on column public.user_nutrition_target.saturated_fat_g_max is '每日饱和脂肪上限（克）';
comment on column public.user_nutrition_target.carbohydrate_g_min is '每日碳水化合物下限（克）';
comment on column public.user_nutrition_target.carbohydrate_g_max is '每日碳水化合物上限（克）';
comment on column public.user_nutrition_target.dietary_fiber_g_min is '每日膳食纤维下限（克）';
comment on column public.user_nutrition_target.vitamin_a_ug_rae_min is '每日维生素A下限（微克RAE）';
comment on column public.user_nutrition_target.vitamin_b1_mg_min is '每日维生素B1下限（毫克）';
comment on column public.user_nutrition_target.vitamin_b2_mg_min is '每日维生素B2下限（毫克）';
comment on column public.user_nutrition_target.vitamin_b6_mg_min is '每日维生素B6下限（毫克）';
comment on column public.user_nutrition_target.vitamin_b12_ug_min is '每日维生素B12下限（微克）';
comment on column public.user_nutrition_target.vitamin_c_mg_min is '每日维生素C下限（毫克）';
comment on column public.user_nutrition_target.vitamin_d_ug_target is '每日维生素D目标值（微克）';
comment on column public.user_nutrition_target.calcium_mg_min is '每日钙下限（毫克）';
comment on column public.user_nutrition_target.iron_mg_min is '每日铁下限（毫克）';
comment on column public.user_nutrition_target.sodium_mg_max is '每日钠上限（毫克）';
comment on column public.user_nutrition_target.salt_equivalent_g_max is '每日食盐相当量上限（克）';
comment on column public.user_nutrition_target.potassium_mg_min is '每日钾下限（毫克）';

alter table public.user_nutrition_target disable row level security;
grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on public.user_nutrition_target to anon, authenticated;
grant all privileges on public.user_nutrition_target to service_role;
grant usage, select, update on sequence public.user_nutrition_target_id_seq to anon, authenticated, service_role;

insert into public.user_nutrition_target (
  user_id, sex, birth_date, age, age_band, height_cm, current_weight_kg, target_weight_kg, reference_weight_kg, body_fat_pct, activity, bmi, menstruation, ckd_stage, goals, health_tags, applied_rules,
  energy_kcal_min, energy_kcal_max, protein_g_min, protein_g_max, fat_g_min, fat_g_max, saturated_fat_g_max, carbohydrate_g_min, carbohydrate_g_max, dietary_fiber_g_min, vitamin_a_ug_rae_min, vitamin_b1_mg_min, vitamin_b2_mg_min, vitamin_b6_mg_min, vitamin_b12_ug_min, vitamin_c_mg_min, vitamin_d_ug_target, calcium_mg_min, iron_mg_min, sodium_mg_max, salt_equivalent_g_max, potassium_mg_min
) values (
  '09909ed0-70ca-4c96-93ed-ba3301573a75', 'male', '1991-10-21', 34, '30-49', 169, 100, 90, 90, null, 'low', 35, null, null, '["loss","glucose","pressure","lipids"]', '["hypertension","sugarRisk","tg"]', '{"weightLoss":true,"glucoseControl":true,"bloodPressureControl":true,"lipidControl":true,"higherFiber":true,"ckdSafetyOverride":false,"anemiaWarning":false,"uricAcidMonitoring":false}',
  2250, 2475, 73.1, 123.8, 50, 68.8, 19.3, 281.3, 371.3, 25, 900, 1.2, 1.7, 1.5, 4, 100, 9, 750, 7.5, 2362, 6, 3000
);

insert into public.user_nutrition_target (
  user_id, sex, birth_date, age, age_band, height_cm, current_weight_kg, target_weight_kg, reference_weight_kg, body_fat_pct, activity, bmi, menstruation, ckd_stage, goals, health_tags, applied_rules,
  energy_kcal_min, energy_kcal_max, protein_g_min, protein_g_max, fat_g_min, fat_g_max, saturated_fat_g_max, carbohydrate_g_min, carbohydrate_g_max, dietary_fiber_g_min, vitamin_a_ug_rae_min, vitamin_b1_mg_min, vitamin_b2_mg_min, vitamin_b6_mg_min, vitamin_b12_ug_min, vitamin_c_mg_min, vitamin_d_ug_target, calcium_mg_min, iron_mg_min, sodium_mg_max, salt_equivalent_g_max, potassium_mg_min
) values (
  'c0db971f-d334-46ec-9080-ce9c64617dd0', 'male', '1992-03-29', 34, '30-49', 173, 103.8, 95, 95, null, 'low', 34.7, null, null, '["loss","glucose"]', '["tg"]', '{"weightLoss":true,"glucoseControl":true,"bloodPressureControl":false,"lipidControl":true,"higherFiber":true,"ckdSafetyOverride":false,"anemiaWarning":false,"uricAcidMonitoring":false}',
  2375, 2613, 77.2, 130.7, 52.8, 72.6, 20.3, 296.9, 391.9, 25, 900, 1.2, 1.7, 1.5, 4, 100, 9, 750, 7.5, 2953, 7.5, 3000
);

insert into public.user_nutrition_target (
  user_id, sex, birth_date, age, age_band, height_cm, current_weight_kg, target_weight_kg, reference_weight_kg, body_fat_pct, activity, bmi, menstruation, ckd_stage, goals, health_tags, applied_rules,
  energy_kcal_min, energy_kcal_max, protein_g_min, protein_g_max, fat_g_min, fat_g_max, saturated_fat_g_max, carbohydrate_g_min, carbohydrate_g_max, dietary_fiber_g_min, vitamin_a_ug_rae_min, vitamin_b1_mg_min, vitamin_b2_mg_min, vitamin_b6_mg_min, vitamin_b12_ug_min, vitamin_c_mg_min, vitamin_d_ug_target, calcium_mg_min, iron_mg_min, sodium_mg_max, salt_equivalent_g_max, potassium_mg_min
) values (
  'e0d252c1-350c-4812-abd7-219e16804448', 'male', '1989-11-10', 36, '30-49', 169, 92, 95, 92, null, 'low', 32.2, null, null, '["muscle","glucose","lipids"]', '["sugarRisk","tg","diabetes"]', '{"weightLoss":false,"glucoseControl":true,"bloodPressureControl":false,"lipidControl":true,"higherFiber":true,"ckdSafetyOverride":false,"anemiaWarning":false,"uricAcidMonitoring":false}',
  2300, 2760, 128.8, 147.2, 51.1, 76.7, 21.5, 287.5, 414, 25, 900, 1.2, 1.7, 1.5, 4, 100, 9, 750, 7.5, 2953, 7.5, 3000
);
