create table public.diet_daily_report (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    user_id uuid not null,
    target_date date not null,
    status text not null default 'pending_confirmation',
    album_ids bigint[] not null default '{}',
    summary text,
    breakfast_advice text,
    lunch_advice text,
    dinner_advice text,
    future_attention text,
    health_context text,
    error_message text,
    submitted_at timestamp with time zone,
    completed_at timestamp with time zone,
    report_push_at timestamp with time zone,
    constraint diet_daily_report_user_id_target_date_key unique (user_id, target_date),
    constraint diet_daily_report_status_check check (status in (
        'pending_confirmation',
        'analyzing_nutrition',
        'generating_report',
        'completed',
        'nutrition_failed',
        'report_failed'
    ))
);

comment on table public.diet_daily_report is '用户每日饮食分析日报';
comment on column public.diet_daily_report.id is '主键';
comment on column public.diet_daily_report.created_at is '创建时间';
comment on column public.diet_daily_report.user_id is '日报所属用户';
comment on column public.diet_daily_report.target_date is '日报目标日期';
comment on column public.diet_daily_report.status is '日报处理状态：pending_confirmation待用户确认，analyzing_nutrition已提交并分析营养，generating_report生成日报中，completed已完成，nutrition_failed营养分析失败，report_failed日报生成失败';
comment on column public.diet_daily_report.album_ids is '生成日报使用的相册ID列表';
comment on column public.diet_daily_report.summary is '日报摘要';
comment on column public.diet_daily_report.breakfast_advice is '早餐建议';
comment on column public.diet_daily_report.lunch_advice is '午餐建议';
comment on column public.diet_daily_report.dinner_advice is '晚餐建议';
comment on column public.diet_daily_report.future_attention is '后续注意事项';
comment on column public.diet_daily_report.health_context is '健康背景信息';
comment on column public.diet_daily_report.error_message is '处理失败信息';
comment on column public.diet_daily_report.submitted_at is '日报提交时间';
comment on column public.diet_daily_report.completed_at is '日报完成时间';
comment on column public.diet_daily_report.report_push_at is '日报推送时间';

create index idx_diet_daily_report_user_date
    on public.diet_daily_report using btree (user_id, target_date desc);
create index idx_diet_daily_report_status
    on public.diet_daily_report using btree (status);

alter table public.diet_daily_report disable row level security;

grant select, insert, update, delete on public.diet_daily_report to anon, authenticated;
grant all privileges on public.diet_daily_report to service_role;
grant usage, select, update on sequence public.diet_daily_report_id_seq to anon, authenticated, service_role;
