create table public.harvest_item (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    harvest_id bigint not null references public.harvest(id) on delete cascade,
    sort_order integer not null,
    text text not null default '',
    link text,
    status smallint not null default 0,
    constraint harvest_item_sort_order_check check (sort_order >= 0),
    constraint harvest_item_text_or_link_check check (btrim(text) <> '' or link is not null),
    constraint harvest_item_status_check check (status in (0, 1)),
    constraint harvest_item_harvest_order_key unique (harvest_id, sort_order)
);

comment on table public.harvest_item is '旅程记录中的逐行事项';
comment on column public.harvest_item.id is '主键';
comment on column public.harvest_item.created_at is '创建时间';
comment on column public.harvest_item.harvest_id is '所属旅程记录ID';
comment on column public.harvest_item.sort_order is '正文中的行顺序，从0开始';
comment on column public.harvest_item.text is '该行除链接外的文字';
comment on column public.harvest_item.link is '从该行提取的链接';
comment on column public.harvest_item.status is '完成状态：0未完成，1已完成';

alter table public.harvest_item disable row level security;

grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on public.harvest_item to anon, authenticated;
grant all privileges on public.harvest_item to service_role;
grant usage, select, update on sequence public.harvest_item_id_seq to anon, authenticated, service_role;
