import { NextResponse } from 'next/server';
export const dynamic='force-dynamic';
const Y='https://query1.finance.yahoo.com/v8/finance/chart/';
const DAY='2026-09-10';
const r=(n,d=4)=>Number(Number(n).toFixed(d));
function fmtDate(ts,tz){const p=new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(ts*1000));const g=k=>p.find(x=>x.type===k)?.value;return `${g('year')}-${g('month')}-${g('day')}`}
function md(s){return s.slice(5).replace('-','/')}
function wd(s){const [y,m,d]=s.split('-').map(Number);return ['日','一','二','三','四','五','六'][new Date(Date.UTC(y,m-1,d)).getUTCDay()]}
function wz(c){if(c===0)return '晴';if(c===1||c===2)return '晴時々曇';if(c===3)return '曇';if(c===45||c===48)return '霧';if(c>=51&&c<=57)return '小雨';if(c>=61&&c<=63)return '雨';if(c===65||c===66||c===67)return '強雨';if(c>=71&&c<=77)return '雪';if(c>=80&&c<=82)return '驟雨';if(c>=85&&c<=86)return '雪';if(c>=95)return '雷雨';return '曇'}
async function chart(sym){const res=await fetch(Y+encodeURIComponent(sym)+'?range=1y&interval=1d&events=history',{cache:'no-store',headers:{'user-agent':'Mozilla/5.0'}});if(!res.ok)throw new Error(sym+':'+res.status);const j=await res.json(),z=j.chart.result?.[0];if(!z)throw new Error(sym+':empty');const tz=z.meta.exchangeTimezoneName||'UTC',ts=z.timestamp||[],cl=z.indicators.quote?.[0]?.close||[];const pts=ts.map((t,i)=>({d:fmtDate(t,tz),v:cl[i]})).filter(x=>Number.isFinite(x.v));if(pts.length<100)throw new Error(sym+':few points');const latest=pts.at(-1),prev=pts.at(-2);const cutoff=new Date(latest.d+'T00:00:00Z');cutoff.setUTCDate(cutoff.getUTCDate()-36);const m1=pts.filter(x=>new Date(x.d+'T00:00:00Z')>=cutoff).slice(-26);const weeks=new Map();for(const p of pts){const d=new Date(p.d+'T00:00:00Z');const day=(d.getUTCDay()+6)%7;d.setUTCDate(d.getUTCDate()-day);weeks.set(d.toISOString().slice(0,10),p)}const y1=[...weeks.values()].slice(-53);return {latest,prev,m1,y1}}
async function weather(lat,lon){const q=new URLSearchParams({latitude:String(lat),longitude:String(lon),hourly:'temperature_2m,precipitation,precipitation_probability,weather_code,wind_speed_10m,relative_humidity_2m,uv_index',daily:'weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,wind_speed_10m_max,relative_humidity_2m_mean,uv_index_max',timezone:'Asia/Tokyo',forecast_days:'7'});const res=await fetch('https://api.open-meteo.com/v1/forecast?'+q,{cache:'no-store'});if(!res.ok)throw new Error('weather:'+res.status);const j=await res.json(),h=j.hourly,d=j.daily,ids=h.time.map((t,i)=>({t,i})).filter(x=>x.t.startsWith(DAY));if(ids.length!==24||d.time?.length!==7)throw new Error('weather incomplete');return {hourly:ids.map(({t,i})=>[+t.slice(11,13),r(h.temperature_2m[i],1),r(h.precipitation[i],1),r(h.wind_speed_10m[i],1),wz(h.weather_code[i]),h.uv_index[i]==null?null:r(h.uv_index[i],2)]),daily:d.time.map((dt,i)=>[md(dt),wd(dt),wz(d.weather_code[i]),r(d.temperature_2m_max[i],1),r(d.temperature_2m_min[i],1),d.precipitation_probability_max[i],`最高${d.precipitation_probability_max[i]}%`,r(d.wind_speed_10m_max[i],1),d.relative_humidity_2m_mean[i]==null?null:Math.round(d.relative_humidity_2m_mean[i]),d.uv_index_max[i]==null?null:r(d.uv_index_max[i],2),null])}}
function asset(name,x){return {name,last:r(x.latest.v),prev:r(x.prev.v),asof:md(x.latest.d),m:x.m1.map(p=>[md(p.d),r(p.v)]),y:x.y1.map(p=>[md(p.d),r(p.v)])}}
export async function GET(){try{const [kin,shibu,kuwa,gspc,qqqm,n225,twii,usdjpy,cnyjpy,twdjpy]=await Promise.all([weather(35.6973,139.8133),weather(35.6595,139.7005),weather(35.0622,136.6839),chart('^GSPC'),chart('QQQM'),chart('^N225'),chart('^TWII'),chart('JPY=X'),chart('CNYJPY=X'),chart('TWDJPY=X')]);const D={w:{'錦糸町（墨田區）':kin,'澀谷':shibu,'桑名（三重縣桑名市）':kuwa},s:[asset('S&P 500',gspc),asset('QQQM',qqqm),asset('日經 225',n225),asset('台灣加權',twii)],f:[asset('USD / JPY',usdjpy),asset('CNY / JPY',cnyjpy),asset('TWD / JPY',twdjpy)]};return new NextResponse('const D='+JSON.stringify(D)+';\n',{headers:{'content-type':'text/javascript; charset=utf-8','cache-control':'no-store'}})}catch(e){return NextResponse.json({error:String(e?.stack||e)},{status:500})}}
